Blog/urls.py
from django.urls import path,re_path
from .views import *
urlpatterns = [


	re_path(r'post/(?P<pk>[\w-]+)/$', post_detail  , name='post_detail'),
	path('', blog  , name='blog'),

]

Dashboard/urls.py
from django.urls import path,include ,re_path
from .views import *
urlpatterns = [
    path('', dashboard , name='dashboard' ),
    path('trainings/all/', all_trainings , name='all_trainings' ),
    path('trainings/add/', add_training , name='add_training' ),
    path('orders/all/', orders , name='orders' ),
    re_path(r'training/section/(?P<pk>[\w-]+)/$', dash_section_detail , name='dash_section_detail' ),
    re_path(r'training/(?P<pk>[\w-]+)/$', dash_training_detail , name='dash_training_detail' ),
    re_path(r'training/(?P<pk>[\w-]+)/del/$', del_training , name='del_training' ),
    re_path(r'training/section/(?P<pk>[\w-]+)/del/$', del_section , name='del_section' ),
    re_path(r'training/section/course/(?P<pk>[\w-]+)/$', dash_course_detail , name='dash_course_detail' ),
    re_path(r'training/section/course/(?P<pk>[\w-]+)/del/$', del_course , name='del_course' ),

    
    path('posts/add/', add_post , name='add_post' ),
    path('posts/all/', all_posts , name='all_posts' ),
    re_path(r'post/(?P<pk>[\w-]+)/$', dash_post_detail , name='dash_post_detail' ),
    re_path(r'post/(?P<pk>[\w-]+)/del/$', del_post , name='del_post' ),

    path('categories/all/', categories , name='categories' ),
    re_path(r'category/(?P<pk>[\w-]+)/$', category_detail , name='category_detail' ),
    re_path(r'category/(?P<pk>[\w-]+)/del/$', del_category , name='del_category' ),

    path('comments/all/', comments , name='comments' ),
    re_path(r'comment/(?P<pk>[\w-]+)/del/$', del_comment , name='del_comment' ),
    
    path('content/', content , name='content' ),
    path('contact/', contact , name='contact' ),

    path('videos/all/', videos , name='videos' ),

    re_path(r'video/(?P<pk>[\w-]+)/$', video_detail , name='video_detail' ),
    re_path(r'video/(?P<pk>[\w-]+)/del/$', del_video , name='del_video' ),

    path('users/all/', users , name='users' ),
    re_path(r'user/(?P<pk>[\w-]+)/$', user_detail , name='user_detail' ),
    re_path(r'user/(?P<pk>[\w-]+)/del/$', del_user , name='del_user' ),
]

Training/urls.py
from django.urls import path, include, re_path
from .views import *
urlpatterns = [
	path('' , trainings , name='trainings' ),
	path('test/' , test , name='test' ),
	path('completed/' , completed , name='completed' ),
	path('my-trainings' , my_trainings , name='my_trainings' ),
	re_path(r'course/(?P<course_pk>[\w-]+)/$' , course_detail , name='course_detail' ),
	re_path(r'payment/(?P<pk>[\w-]+)/$' , payment , name='payment' ),
	re_path(r'active/(?P<pk>[\w-]+)/$' , active_training , name='active_training' ),
	re_path(r'deactivate/(?P<pk>[\w-]+)/$' , deactivate_training , name='deactivate_training' ),
	re_path(r'(?P<training_pk>[\w-]+)/$' , training_detail , name='training_detail' ),
]

Dashboard/models.py
from django.db import models

# Create your models here.

Training/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from Accounts.models import User
from django.utils.translation import gettext_lazy as _

# Create your models here.


class Training(models.Model):

	STATUS = (
		(0,"مسودة"),
		(1,"ينشر")
	)

	title = models.CharField(verbose_name=_('عنوان الدورة'),max_length=250 )
	content = RichTextUploadingField(verbose_name=_('المحتوى'),)
	image = models.ImageField(verbose_name=_('الصورة'),null=True)
	description = models.TextField(verbose_name=_('الوصف'),max_length=250 , blank=True,null=True)
	price = models.DecimalField(verbose_name=_('الثمن'),default=0,max_digits=7, decimal_places=2)
	price_dzd = models.DecimalField(verbose_name=_('الثمن'),default=0,max_digits=7, decimal_places=2)
	nb_purchase = models.IntegerField(verbose_name=_('عدد المشتريات'),default=0)
	created_on = models.DateTimeField(auto_now_add=True , null=True)
	statut = models.IntegerField(verbose_name=_('الحالة'),choices=STATUS, default=1)


	class Meta:
		ordering = ['-created_on']
		verbose_name = _('دورة')
		verbose_name_plural = _('الدورات')


	def __str__(self):
		return	self.title


class Section(models.Model):
	title = models.CharField(verbose_name=_('عنوان الوحدة'),max_length=250 )
	# description = models.TextField(verbose_name=_('الوصف'),max_length=250 , blank=True,null=True)
	content = RichTextUploadingField(verbose_name=_('المحتوى'),)
	training = models.ForeignKey(Training , verbose_name=_('الدورة'),on_delete=models.CASCADE )
	order = models.IntegerField(verbose_name=_('ترتيب الوحدة'),default=0)

	class Meta:
		ordering = ['order']
		verbose_name = _('الوحدة')
		verbose_name_plural = _('الوحدات')

	def __str__(self):
		return	self.title

class Course(models.Model):
	title = models.CharField(verbose_name=_('عنوان الدرس'),max_length=250 , blank=True,null=True)
	description =  models.TextField(verbose_name=_('الوصف'),max_length=250 , blank=True,null=True)
	content = RichTextUploadingField(verbose_name=_('المحتوى'),)
	section = models.ForeignKey(Section , verbose_name=_('الوحدة') ,on_delete=models.CASCADE )
	order = models.IntegerField(verbose_name=_('ترتيب الدرس'),default=0)
	opened = models.BooleanField(verbose_name=_('درس مفتوح'),default=False)

	class Meta:
		ordering = ['order']
		verbose_name = _('الدرس')
		verbose_name_plural = _('الدروس')

	def __str__(self):
		return	self.title
class UserTraining(models.Model):
	user = models.ForeignKey(User , on_delete=models.CASCADE,verbose_name=_('المستخدم'),blank=False,null=False)
	training = models.ForeignKey(Training , on_delete=models.CASCADE,verbose_name=_('الدورة'),blank=False,null=False)
	active = models.BooleanField(verbose_name=_('فعال'),default=False)
	purchase_date = models.DateField(verbose_name=_('تاريخ الشراء'),auto_now_add=True)
  
	class Meta:
		unique_together = (("user", "training"),)
		verbose_name = _('الطلب')
		verbose_name_plural = _('الطلبات')
	
	def __str__(self):
		return	f'{self.training.title} {self.user.get_full_name()}'

Dashboard/views.py
from django.shortcuts import render ,get_object_or_404 ,redirect
from Training.models import *
from Blog.models import *
from .forms import *
from django.contrib 				import messages
from django.contrib.auth.decorators import user_passes_test
from Accounts.models import User
from Accounts.forms import UserAdminChangeForm ,ProfileUpdateForm , UserAdminCreationForm
def is_admin(user):
	
	if user.is_authenticated and user.is_admin:
		return  True
	else:
		return False


@user_passes_test(is_admin)
def dashboard(request):
	template_name = 'pages/dashboard.html'

	args = {

	}

	return render(request, template_name , args)



@user_passes_test(is_admin)
def all_trainings(request):
	template_name = 'training/all.html'
	trainings = Training.objects.all()
	training_form = TrainingForm(request.POST or None  , request.FILES or None)
	if request.method =="POST":
		if training_form.is_valid():
			instance = training_form.save()
			messages.success(request , 'تم التعديل بنجاح')
			return redirect('dash_training_detail' , pk=instance.pk)
	
	args = {
		'trainings':trainings,
		'training_form':training_form,
	}

	return render(request, template_name , args)

@user_passes_test(is_admin)
def add_training(request):
	template_name = 'training/add_training.html'
	form = TrainingForm(request.POST or None , request.FILES or None)
	if request.method == 'POST':

		if form.is_valid():
			try:
				instance = form.save()
				messages.success(request, 'تمت الإضافة بنجاح' )
				return redirect('dash_training_detail' , pk=instance.pk)
			except Exception as e:
				messages.error(request, f'لم يتم  إضافة الدورة {e}')

	args = {
		'form':form,
	}
	return render(request , template_name , args)	



@user_passes_test(is_admin)
def dash_training_detail(request , pk):
	template_name = "training/dash_training_detail.html"
	training = get_object_or_404(Training , pk=pk)
	training_form = TrainingForm(request.POST or None ,request.FILES or None, instance=training)
	section_form = SectionForm(request.POST or None , pk , training_id = pk)
	if request.method =='POST':
		if 'training' in request.POST:

			if training_form.is_valid():
				training_form.save()
				messages.success(request , 'تم التعديل بنجاح')
				return redirect('dash_training_detail' , pk=pk)

		if 'add_section' in request.POST:
			if section_form.is_valid():
				instance = section_form.save(commit=False)
				instance.training = training
				instance.save()
				messages.success(request, 'تم إضافة الوحدة بنجاح')
				return redirect('dash_section_detail' , pk=instance.pk)
				
	args = {
		'form':training_form,
		'section_form':section_form,
		'training':training,
	}

	return render(request , template_name , args)


@user_passes_test(is_admin)
def del_training(request , pk):
	training = get_object_or_404(Training , pk=pk)
	try:
		training.delete()
		messages.success(request, 'تم حذف الدورة بنجاح')
		return redirect('all_trainings')
	except Exception as e:
		messages.error(request, f'لم يتم حذف الدورة  {e}')
		return redirect('all_trainings')
	


@user_passes_test(is_admin)
def dash_section_detail(request , pk):
	template_name = "training/dash_section_detail.html"
	section = get_object_or_404(Section , pk=pk)
	form = SectionForm(request.POST or None , instance=section , training_id = section.training.pk)
	course_form = CourseForm(request.POST or None ,  section_id=section.id)
	if request.method =='POST':
		if 'section' in request.POST:

			if form.is_valid():
				form.save()
				messages.success(request , 'تم التعديل بنجاح')
				return redirect('dash_section_detail' , pk=pk)

		if 'add_course' in request.POST:
			if course_form.is_valid():
				instance = course_form.save(commit=False)
				instance.section = section
				instance.save()
				messages.success(request, 'تم الإضافة  بنجاح')
				return redirect('dash_section_detail' , pk=pk)
						


	args = {
		'form':form,
		'section':section,
		'course_form':course_form,
	}

	return render(request , template_name , args)



@user_passes_test(is_admin)
def del_section(request , pk):
	section = get_object_or_404(Section , pk=pk)
	training = section.training
	try:
		section.delete()
		messages.success(request, 'تم حذف الوحدة بنجاح')
		return redirect('dash_training_detail' , pk=training.pk )
	except Exception as e:
		messages.error(request, f'لم يتم حذف الوحدة  {e}')
		return redirect('dash_training_detail' , pk=training.pk )



@user_passes_test(is_admin)
def dash_course_detail(request , pk):
	template_name = "training/dash_course_detail.html"
	course = get_object_or_404(Course , pk=pk)
	form = CourseForm(request.POST or None , instance=course , section_id=course.section.id)
	if request.method =='POST':
	
		if form.is_valid():
			form.save()
			messages.success(request , 'تم التعديل بنجاح')
			return redirect('dash_course_detail' , pk=pk)

					


	args = {
		'form':form,
		'course':course,
	}

	return render(request , template_name , args)



@user_passes_test(is_admin)	
def del_course(request , pk):
	course = get_object_or_404(Course , pk=pk)
	section = course.section
	try:
		course.delete()
		messages.success(request, 'تم حذف الدرس بنجاح')
		return redirect('dash_section_detail' , pk=section.pk )
	except Exception as e:
		messages.error(request, f'لم يتم حذف الوحدة  {e}')
		return redirect('dash_section_detail' , pk=section.pk )
	

@user_passes_test(is_admin)
def orders(request):
	template_name  = 'training/orders.html'
	orders = UserTraining.objects.all().order_by('purchase_date')
	form = UserTrainingForm(request.POST or None)
	if request.method == "POST":
		if form.is_valid():
			try:

				form.save()
				messages.success(request, 'تمت الإضافة بنجاح')
			except Exception as e:
				messages.error(request, f'لم تتم الإضافة {e}')

			return redirect('orders' )

	args = {
		'orders':orders,
		'form':form,
	}

	return render(request , template_name , args)





@user_passes_test(is_admin)
def all_posts(request ):
	template_name = "blog/posts.html"
	posts = Post.objects.all()
	form = PostForm(request.POST or None , request.FILES or None)
	if request.method=='POST':
		if form.is_valid():
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			messages.success(request, 'تمت الإضافة بنجاح')
			return redirect('posts'  )
		


	args = {
		'posts':posts,
		'form':form,
	}

	return render(request , template_name , args)


@user_passes_test(is_admin)
def dash_post_detail(request , pk):
	template_name = "blog/dash_post_detail.html"
	post = get_object_or_404(Post , pk=pk)
	form = PostForm(request.POST or None , request.FILES or None, instance=post)
	if request.method =='POST':
	
		if form.is_valid():
			form.save()
			messages.success(request , 'تم التعديل بنجاح')
			return redirect('dash_post_detail' , pk=pk)
	


	args = {
		'form':form,
		'post':post,
	}

	return render(request , template_name , args)



@user_passes_test(is_admin)	
def del_post(request , pk):
	post = get_object_or_404(Post , pk=pk)
	try:
		post.delete()
		messages.success(request, 'تم حذف الدرس بنجاح')
	except Exception as e:
		messages.error(request, f'لم يتم حذف المقال  {e}')
	
	return redirect('all_posts')


@user_passes_test(is_admin)
def categories(request):
	template_name = 'blog/categories.html'
	categories = Category.objects.all()
	form = CategoryForm(request.POST or None )
	if request.method == "POST" :
		if form.is_valid():
			instance = form.save()
			messages.success(request, 'تمت الإضافة بنجاح')
			return redirect('category_detail' , pk=instance.pk)
	args = {
		'categories':categories,
		'form':form,
	}

	return render(request , template_name , args)

@user_passes_test(is_admin)
def category_detail(request , pk):
	template_name = 'blog/category_detail.html'
	category = get_object_or_404(Category , pk=pk)
	form = CategoryForm(request.POST or None , instance=category)
	
	if request.method == "POST" :
		if form.is_valid():
			form.save()
			messages.success(request , 'تم التعديل بنجاح')

	args = {
		'category':category,
		'form':form,
	}

	return render(request , template_name , args)
	

@user_passes_test(is_admin)	
def del_category(request , pk):
	category = get_object_or_404(Category , pk=pk)
	try:
		category.delete()
		messages.success(request, 'تم حذف الفئة بنجاح')
	except Exception as e:
		messages.error(request, f'لم يتم حذف المقال  {e}')
	
	return redirect('categories')
	

@user_passes_test(is_admin)
def comments(request):
	template_name = 'blog/comments.html'
	comments = Comment.objects.all()

	args = {
		'comments':comments,
	}

	return render(request , template_name , args)

@user_passes_test(is_admin)	
def del_comment(request , pk):
	comment = get_object_or_404(Comment , pk=pk)
	try:
		comment.delete()
		messages.success(request, 'تم حذف التعليق بنجاح')
	except Exception as e:
		messages.error(request, f'لم يتم حذف التعليق  {e}')
	
	return redirect('comments')
	

@user_passes_test(is_admin)
def add_post(request):
	template_name = 'blog/add_post.html'
	form = PostForm(request.POST or None , request.FILES or None)
	if request.method == 'POST':
			
		if form.is_valid():
			try:
				instance = form.save(commit=False)
				instance.author = request.user
				instance.save()
				messages.success(request, 'تمت الإضافة بنجاح' )
				return redirect('dash_post_detail' , pk=instance.pk)
			except Exception as e:
				messages.error(request, f'لم يتم  إضافة الدورة {e}')

	args = {
		'form':form,
	}
	return render(request , template_name , args)

@user_passes_test(is_admin)
def content(request):
	template_name = 'parameters/content.html'
	instance = Content.objects.all()[0]
	form = ContentForm(request.POST or None , request.FILES or None , instance=instance)
	if request.method == 'POST':
			
		if form.is_valid():
			try:
				instance = form.save()
				messages.success(request, 'تم التعديل بنجاح' )
				return redirect('content')
			except Exception as e:
				messages.error(request, f'لم يتم  إضافة الدورة {e}')

	args = {
		'form':form,
	}
	return render(request , template_name , args)

@user_passes_test(is_admin)
def contact(request):

Dashboard/templates/training/dash_section_detail.html
{% extends "dash_base/base.html" %}
{% load static %}
{% block title %}{{section.title}}{% endblock title %}
{% block page_title %}{{section.title}}{% endblock page_title %}

{% block breadcrumb %}
    <li class=""><a href="{% url 'all_trainings' %}">جميع الدورات </a></li>
    <li class=""><a href="{% url 'dash_training_detail' pk=section.training.pk %}">{{section.training.title}}</a> </li>
    <li class="active">{{section.title}} </li>
    
{% endblock  %}

{% block body %}

<div class="col-md-12">
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
            <div class="alert alert-success" role="alert">{{message}}</div>
        {% else %}
            <div class="alert alert-danger" role="alert">{{message}}</div>
            
        {% endif %}
    {% endfor %}
</div>
<div class="col-md-12">
    <div class="panel panel-card recent-activites">
        <!-- Start .panel -->
        <div class="panel-heading">
            <h4 class="panel-title">تفاصيل  الدورة</h4>
            <div class="panel-actions">
                <a href="#" class="panel-action panel-action-toggle" data-panel-toggle=""></a>
                <!-- <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss=""></a> -->
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
            	<form method="POST" enctype="multipart/form-data">{% csrf_token %}
            		<div class="col-md-12">
	            			
			        	{{form.media }}
					    {{form.as_p }}
					    <input type="submit" name="section" value="تعديل" class="btn btn-sm btn-primary pull-right m-t-n-xs">            		
					</div>
            	</form>
      		</div>
        </div>
    </div><!-- End .panel --> 
</div>

  <div class="col-md-12">
        <div class="panel panel-card ">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title"> جميع الدروس</h4>
                <div class="panel-actions">
                    <button  type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal" >إضافة درس جديد</button>
                    <a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
                     <div class="modal fade " id="exampleModal" tabindex="-2" role="dialog" aria-labelledby="exampleModalLabel">
                                      <div class="modal-dialog modal-lg" role="document">
                                        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                                            <div class="modal-content" style="    margin-top: 100px;">
                                              <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title" id="exampleModalLabel">إضافة درس</h4>
                                              </div>
                                              <div class="modal-body">
                                                    {{course_form.media }}
                                                    {{course_form.as_p}}
                                              </div>
                                              <div class="modal-footer">
                                                <!-- <button type="button" class="btn btn-primary">إضافة</button> -->
                                                <input type="submit" name="add_course" value="إضافة" class="btn btn-sm btn-primary">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق</button>
                                              </div>
                                            </div>
                                        </form>
                                      </div>
                                    </div>
                    <!-- <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a> -->
                </div>
            </div>
            <div class="panel-body">
                <table id="responsive-datatables" class="table table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>الترتيب</th>
                            <th> عنوان الدورة</th>
                            <th>النشاط</th>
                        </tr>
                    </thead>
                    <tbody>
                    	{% for course in section.course_set.all %}
                    		
                            <tr>
                                <td>
                    				<a href="{% url 'dash_course_detail' pk=course.pk %}">
                                		{{course.order}}
                    				</a>	
                            	</td>
                                <td>{{course.title}}</td>
                                <td>
                                    <a href="{% url 'dash_course_detail' pk=course.pk %}" class=""><i class="fa fa-edit"></i></a>
                                    <a href="#" data-toggle="modal" data-target="#exampleModal{{course.pk}}"><i class="fa fa-trash" style="color: #df645d;"></i></a>
                                    <div class="modal fade " id="exampleModal{{course.pk}}" tabindex="-2" role="dialog" aria-labelledby="exampleModalLabel">
                                      <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content" style="    margin-top: 100px;">
                                              <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title" id="exampleModalLabel">حذف دورة</h4>
                                              </div>
                                              <div class="modal-body">
                                                   <p>هل أنت متاكد من حذف {{course.title}}؟</p>
                                              </div>
                                              <div class="modal-footer">
                                                <!-- <button type="button" class="btn btn-primary">حذف</button> -->
                                                <a href="{% url 'del_course' pk=course.pk %}" class="btn btn-sm btn-danger">نعم</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق</button>
                                              </div>
                                            </div>
                                      </div>
                                    </div>
                                </td>
                            </tr>
                    	{% endfor %}
                    </tbody>
                </table>
            </div>
        </div><!-- End .panel -->  
    </div><!--end .col-->
{% endblock body %}



{% block script %}
    <script src="{% static 'dashboard/js/data-tables/jquery.dataTables.js' %}"></script>
    <script src="{% static 'dashboard/js/data-tables/dataTables.tableTools.js' %}"></script>
    <script src="{% static 'dashboard/js/data-tables/dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'dashboard/js/data-tables/dataTables.responsive.js' %}"></script>
    <script src="{% static 'dashboard/js/data-tables/tables-data.js' %}"></script>
{% endblock script %}

Dashboard/templates/training/dash_training_detail.html
{% extends "dash_base/base.html" %}
{% load static %}

{% block title %}{{training.title}}{% endblock title %}
{% block page_title %}{{training.title}}{% endblock page_title %}
{% block breadcrumb %}
    <li class=""><a href="{% url 'all_trainings' %}">جميع الدورات </a></li>
    <li class="active">{{training.title}} </li>
    
{% endblock  %}

{% block body %}

<div class="col-md-12">
	{% for message in messages %}
		{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %} 
			<div class="alert alert-success" role="alert">{{message}}</div>
		{% else %}
			<div class="alert alert-danger" role="alert">{{message}}</div>
		    
		{% endif %}
	{% endfor %}
</div>
<div class="col-md-12">

    <div class="panel panel-card recent-activites">
        <!-- Start .panel -->
        <div class="panel-heading">
            <h4 class="panel-title">تفاصيل  الدورة</h4>
            <div class="panel-actions">
                <a href="#" class="panel-action panel-action-toggle" data-panel-toggle=""></a>
                <!-- <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss=""></a> -->
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
            	<form method="POST" enctype="multipart/form-data">{% csrf_token %}
            		<div class="col-md-12">
	            			
			        	{{form.media }}
					    {{form.as_p }}
					    <input type="submit" name="training" value="تعديل" class="btn btn-sm btn-primary pull-right m-t-n-xs">            		
					</div>
            	</form>
      		</div>
        </div>
    </div><!-- End .panel --> 
</div>

  <div class="col-md-12">
        <div class="panel panel-card ">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title"> جميع الوحدات</h4>
                <div class="panel-actions">
                    <button  type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal" >إضافة وحدة جديدة</button>
                     <div class="modal fade " id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                                      <div class="modal-dialog" role="document">
                                        <form method="POST" enctype="multipart/form-data">{% csrf_token %}
	                                        <div class="modal-content" style="    margin-top: 100px;">
	                                          <div class="modal-header">
	                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	                                            <h4 class="modal-title" id="exampleModalLabel">إضافة وحدة</h4>
	                                          </div>
	                                          <div class="modal-body">
	                                              	{{section_form.as_p}}
	                                          </div>
	                                          <div class="modal-footer">
	                                            <!-- <button type="button" class="btn btn-primary">إضافة</button> -->
                                              	<input type="submit" name="add_section" value="إضافة" class="btn btn-sm btn-primary">
	                                            <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق</button>
	                                          </div>
	                                        </div>
                                        </form>
                                      </div>
                                    </div>
                    <a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>

                    <!-- <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a> -->
                </div>
            </div>
            <div class="panel-body">
                <table id="basic-datatables" class="table table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th> الترتيب</th>
                            <th> عنوان الوحدة</th>
                            <th>النشاط</th>
                        </tr>
                    </thead>
                    <tbody>
                    	{% for section in training.section_set.all %}
                    		
                            <tr>
                                <td>
                    				<a href="{% url 'dash_section_detail' pk=section.pk %}">
                                		{{section.order}}
                    				</a>	
                            	</td>
                                <td>{{section.title}}</td>
                                <td>
                                	<a href="{% url 'dash_section_detail' pk=section.pk %}" class=""><i class="fa fa-edit"></i></a>
                                	<a href="#" data-toggle="modal" data-target="#exampleModal{{section.pk}}"><i class="fa fa-trash" style="color: #df645d;"></i></a>
                                    <div class="modal fade " id="exampleModal{{section.pk}}" tabindex="-2" role="dialog" aria-labelledby="exampleModalLabel">
                                      <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content" style="    margin-top: 100px;">
                                              <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title" id="exampleModalLabel">حذف دورة</h4>
                                              </div>
                                              <div class="modal-body">
                                                   <p>هل أنت متاكد من حذف {{section.title}}؟</p>
                                              </div>
                                              <div class="modal-footer">
                                                <!-- <button type="button" class="btn btn-primary">حذف</button> -->
                                                <a href="{% url 'del_section' pk=section.pk %}" class="btn btn-sm btn-danger">نعم</a>
                                                <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق</button>
                                              </div>
                                            </div>
                                      </div>
                                    </div>
                                </td>
                            </tr>
                    	{% endfor %}
                    </tbody>
                </table>
            </div>
        </div><!-- End .panel -->  
    </div><!--end .col-->



{% endblock body %}



{% block script %}
	<script src="{% static 'dashboard/js/data-tables/jquery.dataTables.js' %}"></script>
	<script src="{% static 'dashboard/js/data-tables/dataTables.tableTools.js' %}"></script>
	<script src="{% static 'dashboard/js/data-tables/dataTables.bootstrap.js' %}"></script>
	<script src="{% static 'dashboard/js/data-tables/dataTables.responsive.js' %}"></script>
	<script src="{% static 'dashboard/js/data-tables/tables-data.js' %}"></script>
{% endblock script %}